exclude: 'docs|.git'
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    # add supported hooks https://pre-commit.com/hooks.html
      - id: check-added-large-files
        # args: ['--maxkb=XXXX']
      - id: check-ast
      - id: check-case-conflict
      # - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      # Run the formatter
      - id: ruff-format

  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      exclude: ^.*\b(migrations)\b.*$
      # See bug: https://github.com/psf/black/issues/2964
      # If possible, run rev: 22.3.0 to obviate the need for pinning click
      # additional_dependencies: ["click==8.0.4"]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
        #    - id: isort
      # name: isort
      # entry: poetry run isort
      # language: system
      # types: [python]
  
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt"]
      # - id: poetry-export
      # args: ["--with", "dev", "-o", "requirements-dev.txt"]
