repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    # add supported hooks https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      exclude: ^.*\b(migrations)\b.*$
      # See bug: https://github.com/psf/black/issues/2964
      # If possible, run rev: 22.3.0 to obviate the need for pinning click
      # additional_dependencies: ["click==8.0.4"]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
